on:
  pull_request:
  push:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends musl-tools
    - run: musl-gcc -s -O3 -static main.c -o rename-exchange
    - run: ./test.sh
