name: main
on:
  pull_request:
  push:
    branches: [master]

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: gcc -D_GNU_SOURCE -s -O3 main.c -o rename-exchange
    - run: ./test.sh
